/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Crossover: typeof import('./components/Crossover.vue')['default']
    DoubleTrackBlock: typeof import('./components/DoubleTrackBlock.vue')['default']
    Geometry: typeof import('./components/turnout/Geometry.vue')['default']
    Signal: typeof import('./components/Signal.vue')['default']
    TrackBlock: typeof import('./components/TrackBlock.vue')['default']
    Turnout: typeof import('./components/turnout/index.vue')['default']
  }
}
